### ISSUE TITLE
Entities that reference each other

### ISSUE THREAD

**Issue by chriseling** [rahmanfadhil/learn-typegraphql#1]
Hi great, article, super helpful.  I've been following your guide and getting a 

ReferenceError: Cannot access 'B' before initialization

when trying to import more than one entity where they reference each other.  Any ideas?

```
@Entity()
export class A extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  @OneToOne(
    () => B,
    b => b.a
  )
  public b!: B;
}

@Entity()
export class B extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  @OneToOne(
    () => A,
    a => a.b
  )
  @JoinColumn()
  public a!: A;
}
```

**Comment by rahmanfadhil** [comment]
To implement a relationship between models, you need to create a custom field resolver. You can read more about it in the [TypeGraphQL docs](https://typegraphql.com/docs/resolvers.html#field-resolvers).

Example:

```ts
@Resolver(of => Recipe)
class RecipeResolver implements ResolverInterface<Recipe> {
  // queries and mutations

  @FieldResolver()
  author(@Root() recipe: Recipe) {
    const recipeRepository = connection.getRepository(Recipe);
    return (await userRepository.find({ relations: ["profile"] })).author // get the recipe's author;
  }
}
```

**Comment by rahmanfadhil** [comment]
Or, you can use the [TypeORM lazy relations](https://typeorm.io/#/eager-and-lazy-relations/lazy-relations) feature, which is super convenient (you don't need to set up custom field resolver).
