### ISSUE TITLE
Recurring Error/Warning

### ISSUE THREAD

**Issue by netlander** [rahmanfadhil/learn-typegraphql#5]
Keep getting this warning in console, not sure how important...

```
No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.
```

BTW the best starter project I've found after days of searching. Thanks.

**Comment by rahmanfadhil** [comment]
Thanks!

This warning has been around for a while. If you want to suppress this warning, I think you can just run `npm install class-validator` to make sure you only use one version of `class-validator`.
